//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///  &lt;appender name=&quot;RollingFileAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///    &lt;lockingModel type=&quot;log4net.Appender.FileAppender+MinimalLock&quot;/&gt;
        ///    &lt;file value=&quot;logs\&quot; /&gt;
        ///    &lt;staticLogFileName value=&quot;false&quot; /&gt;  &lt;!--If true will always should be log to the same file, otherwise false.--&gt;
        ///    &lt;appendToFile value=&quot;true&quot; /&gt;  &lt;!--If false the file will be overwritten, if true the file will be appended to.--&gt;
        ///    &lt;rollingStyle value=&quot;Composite&quot; /&gt;  &lt;!--Options are: Once (Roll files once p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net_AsyncRollingFileTPLForwarder_config {
            get {
                return ResourceManager.GetString("log4net_AsyncRollingFileTPLForwarder_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///  &lt;appender name=&quot;RollingFileAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///    &lt;lockingModel type=&quot;log4net.Appender.FileAppender+MinimalLock&quot;/&gt;
        ///    &lt;file value=&quot;logs\&quot; /&gt;
        ///    &lt;staticLogFileName value=&quot;false&quot; /&gt;  &lt;!--If true will always should be log to the same file, otherwise false.--&gt;
        ///    &lt;appendToFile value=&quot;true&quot; /&gt;  &lt;!--If false the file will be overwritten, if true the file will be appended to.--&gt;
        ///    &lt;rollingStyle value=&quot;Composite&quot; /&gt;  &lt;!--Options are: Once (Roll files once p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net_RollingFileAppender_config {
            get {
                return ResourceManager.GetString("log4net_RollingFileAppender_config", resourceCulture);
            }
        }
    }
}
